# Generated by Django 3.2.6 on 2021-08-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='word',
        ),
    ]
